# Generated by Django 3.1.1 on 2020-09-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Person name', max_length=100)),
                ('age', models.IntegerField(default=0, help_text='Person age')),
                ('address', models.CharField(help_text='Person address', max_length=100)),
                ('work', models.CharField(help_text='Person work', max_length=100)),
            ],
        ),
    ]
