name: Build project
on: [push]
jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          python manage.py test
      - name: Lint with flake8
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.4.6
        with:
          heroku_api_key: "f8244834-f822-4b39-b8b9-a29d90dbe91f"
          heroku_app_name: "shmarov-rsoi-lab1"
          heroku_email: "bambookchos@gmail.com"
      - name: Checkout test repository
        uses: actions/checkout@v2
        with:
          repository: Romanow/person-service-test
          path: integration-tests
          ref: master
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run integration tests
        uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: integration-tests
          wrapper-directory: integration-tests
          arguments: clean test -PtargetUrl=https://shmarov-rsoi-lab1.herokuapp.com
